plugins {
    id 'cpp'
    id 'google-test-test-suite'
    id 'org.wpilib.WPILibRepositoriesPlugin' version '2027.0.0'
    id 'org.wpilib.NativeUtils' version '2027.14.3'
    id 'org.wpilib.GradleVsCode' version '2027.0.0'
}

ext.wpilibVersion = '2027.0.0-alpha-7'
def hostOsName = System.getProperty('os.name')
def hostPlatformName = hostOsName.startsWith('Mac') ? 'osxuniversal' : hostOsName.startsWith('Windows') ? 'windowsx86-64' : 'linuxx86-64'
def cppStandardArgument = hostOsName.startsWith('Windows') ? '/std:c++23preview' : '-std=c++23'
def supportsPrecompiledHeaders =
    !System.getProperty('os.name').startsWith('Mac') &&
    !System.getProperty('os.name').startsWith('Windows')

repositories {
    mavenCentral()
}

if (project.hasProperty('releaseMode')) {
    wpilibRepositories.addAllReleaseRepositories(project)
} else {
    wpilibRepositories.addAllDevelopmentRepositories(project)
}

apply from: 'config.gradle'

nativeUtils {
    exportsConfigs {
        MapleSimCpp {
        }
    }
}

model {
    components {
        MapleSimCpp(NativeLibrarySpec) {
            sources.cpp {
                if (supportsPrecompiledHeaders) {
                    preCompiledHeader 'pch.h'
                }
                source {
                    srcDir 'src/main/native/cpp'
                    include 'maplesim/**/*.cpp'
                }
                source {
                    srcDir 'third_party/box2d/src'
                    include '**/*.cpp'
                }
                exportedHeaders {
                    srcDir 'src/main/native/include'
                    srcDir 'src/main/native/cpp'
                    srcDir 'third_party/box2d/include'
                }
            }

            binaries.all {
                cppCompiler.args cppStandardArgument
            }

            nativeUtils.useRequiredLibrary(it, 'wpilib_shared')
        }
    }

    testSuites {
        MapleSimCppTest(GoogleTestTestSuiteSpec) {
            testing $.components.MapleSimCpp

            sources.cpp {
                source {
                    srcDir 'src/test/native/cpp'
                    include '**/*.cpp'
                }
            }

            binaries.all {
                cppCompiler.args cppStandardArgument
                lib library: 'MapleSimCpp', linkage: 'static'
                if (targetPlatform.name != hostPlatformName) {
                    buildable = false
                }
            }

            nativeUtils.useRequiredLibrary(it, 'wpilib_shared')
            nativeUtils.useRequiredLibrary(it, 'googletest_static')
        }
    }
}

apply from: 'publish.gradle'

wrapper {
    gradleVersion = '9.4.1'
}
