name: CI

on:
  push:
  pull_request:

jobs:
  wrapper-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4

  build-linux:
    needs: wrapper-validation
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Systemcore
            toolchain: installSystemCoreToolchain
            options: -Ponlylinuxsystemcore
          - name: Linux ARM64
            toolchain: installArm64Toolchain
            options: -Ponlylinuxarm64
          - name: Linux x86-64
            toolchain: ''
            options: ''
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
      - if: matrix.toolchain != ''
        run: ./gradlew ${{ matrix.toolchain }}
      - run: ./gradlew build -PreleaseMode ${{ matrix.options }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: build/allOutputs

  build-desktop:
    needs: wrapper-validation
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            name: Windows x86-64
            architecture: x64
            options: -Pbuildalldesktop
          - os: windows-2022
            name: Windows ARM64
            architecture: x64
            options: -Pbuildwinarm64 -Ponlywindowsarm64
          - os: macos-15
            name: macOS universal
            architecture: aarch64
            options: -Pbuildalldesktop
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          architecture: ${{ matrix.architecture }}
      - run: ./gradlew build -PreleaseMode ${{ matrix.options }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: build/allOutputs

  combine:
    needs: [build-linux, build-desktop]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wpilibsuite/build-tools
      - uses: actions/download-artifact@v4
        with:
          path: combiner/products/build/allOutputs
          pattern: '{Systemcore,Linux ARM64,Linux x86-64,Windows x86-64,Windows ARM64,macOS universal}'
      - run: rsync -a --delete combiner/products/build/allOutputs/*/* combiner/products/build/allOutputs/
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
      - run: ./gradlew publish -Pthirdparty
        working-directory: combiner
      - uses: actions/upload-artifact@v4
        with:
          name: Maven
          path: ~/releases
